"""
Builds the "JAKA" arm decals used by lumi.xml: a texture (assets/jaka_logo.png) and thin curved
meshes (assets/jaka_a2.obj, assets/jaka_a3.obj) that sit on the round joint housings of the arm.

Each decal is a thin piece of a cylinder shell, in the link's own frame (the same frame as the
link's STL), so in lumi.xml the geom needs no pos or quat. Run once after changing a size:

    python3 tools/make_decals.py      (needs numpy and Pillow)
"""
from pathlib import Path

import numpy as np
from PIL import Image, ImageDraw, ImageFont

ASSETS = Path(__file__).resolve().parent.parent / "assets"
FONT = "/System/Library/Fonts/Supplemental/Arial Bold Italic.ttf"
WHITE = (235, 237, 240)        # lumi_white material (0.92 0.93 0.94)
RED = (200, 16, 30)

# name: housing radius (m, the largest radius of the STL in that band), centre angles of the text
#       (rad, around the housing's z axis; one label per angle, both sides of the arm),
#       text height (m), z of the text's middle (m), arc length of the text (m)
DECALS = {
    "jaka_a2": dict(radius=0.0502, angles=(-np.pi / 2, np.pi / 2), height=0.018, z=0.017, width=0.058),
    "jaka_a3": dict(radius=0.0421, angles=(-np.pi / 2, np.pi / 2), height=0.020, z=0.026, width=0.060),
}
LIFT = 0.0006       # decal surface sits 0.6 mm above the housing
THICK = 0.0004      # shell thickness, so the mesh has a volume


def make_texture(path):
    w, h = 1024, 320
    img = Image.new("RGB", (w, h), WHITE)
    draw = ImageDraw.Draw(img)
    font = ImageFont.truetype(FONT, 250)
    box = draw.textbbox((0, 0), "JAKA", font=font)
    x = (w - (box[2] - box[0])) / 2 - box[0]
    y = (h - (box[3] - box[1])) / 2 - box[1]
    draw.text((x, y), "JAKA", font=font, fill=RED)
    img.save(path)


def make_mesh(path, radius, angles, height, z, width):
    verts, uvs, faces = [], [], []

    def v(r, a, zz, u, t):
        verts.append((r * np.cos(a), r * np.sin(a), zz))
        uvs.append((u, t))
        return len(verts)

    for angle in angles:
        add_label(v, faces, radius, angle, height, z, width)

    with open(path, "w") as f:
        f.write("# generated by tools/make_decals.py\n")
        f.writelines(f"v {x:.6f} {y:.6f} {zz:.6f}\n" for x, y, zz in verts)
        f.writelines(f"vt {u:.5f} {t:.5f}\n" for u, t in uvs)
        f.writelines(f"f {a}/{a} {b}/{b} {c}/{c}\n" for a, b, c in faces)


def add_label(v, faces, radius, angle, height, z, width, segments=24):
    span = width / radius
    angles = angle + np.linspace(-span / 2, span / 2, segments + 1)  # left to right as seen from outside
    r_out, r_in = radius + LIFT + THICK, radius + LIFT
    z0, z1 = z - height / 2, z + height / 2
    for i in range(segments):
        a0, a1 = angles[i], angles[i + 1]
        u0, u1 = i / segments, (i + 1) / segments
        # outer face carries the text; the inner face and the rims use a blank corner of the texture
        o = [v(r_out, a0, z0, u0, 0), v(r_out, a1, z0, u1, 0), v(r_out, a1, z1, u1, 1), v(r_out, a0, z1, u0, 1)]
        n = [v(r_in, a0, z0, 0.01, 0.01), v(r_in, a1, z0, 0.01, 0.01), v(r_in, a1, z1, 0.01, 0.01),
             v(r_in, a0, z1, 0.01, 0.01)]
        faces += [(o[0], o[1], o[2]), (o[0], o[2], o[3]), (n[0], n[2], n[1]), (n[0], n[3], n[2]),
                  (n[0], n[1], o[1]), (n[0], o[1], o[0]), (n[3], o[3], o[2]), (n[3], o[2], n[2])]
    for a, i in ((angles[0], 0), (angles[-1], segments)):
        p = [v(r_in, a, z0, 0.01, 0.01), v(r_out, a, z0, 0.01, 0.01), v(r_out, a, z1, 0.01, 0.01),
             v(r_in, a, z1, 0.01, 0.01)]
        faces += [(p[0], p[1], p[2]), (p[0], p[2], p[3])] if i else [(p[0], p[2], p[1]), (p[0], p[3], p[2])]


if __name__ == "__main__":
    ASSETS.mkdir(exist_ok=True)
    make_texture(ASSETS / "jaka_logo.png")
    for name, params in DECALS.items():
        make_mesh(ASSETS / f"{name}.obj", **params)
    print("written to", ASSETS)
